#/bin/bash 

## load modules 
module load R/4.0.4

CONFIG_INITIAL=config_atos
 
#R Env
USING_RENV=${USING_RENV-no}

## DNOT for USER
MAIN_DIR=$(pwd)
CONFIG_DIR=$MAIN_DIR/config
RS_DIR=$MAIN_DIR/R
CONFIG_YAML=$CONFIG_DIR/$CONFIG_INITIAL.yml_${CASE_STUDY}
CONFIG_R=$CONFIG_DIR/$CONFIG_INITIAL.R

##
export MAIN_DIR CONFIG_INITIAL  
export USING_RENV
export CONFIG_DIR RS_DIR CONFIG_YAML CONFIG_R
